# Generated by Django 5.2.10 on 2026-02-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_credentials',
            name='tagline',
            field=models.CharField(blank=True, help_text='Company Tagline', max_length=255, null=True),
        ),
    ]
