# Generated by Django 5.2.10 on 2026-02-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_company_credentials_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_credentials',
            name='website',
            field=models.URLField(blank=True, help_text='Company Website', max_length=255, null=True),
        ),
    ]
