# Generated by Django 5.2.10 on 2026-02-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_credentials',
            name='email',
            field=models.EmailField(blank=True, help_text='Login Email (for authentication)', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company_credentials',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed Password (for authentication)', max_length=128, null=True),
        ),
    ]

