# Generated by Django 4.2.7 on 2026-02-04 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_remove_company_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Company Email', max_length=254)),
                ('password', models.CharField(help_text='Company Password', max_length=255)),
                ('login_logo', models.ImageField(blank=True, help_text='Login Logo', null=True, upload_to='company_login/')),
                ('login_image', models.ImageField(blank=True, help_text='Login Image', null=True, upload_to='company_login/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'ordering': ['-created_at'],
            },
        ),
    ]
