# Generated by Django 4.2.7 on 2026-02-04 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name': 'Company Details', 'verbose_name_plural': 'Company Details'},
        ),
    ]
