# Generated by Django 4.2.7 on 2026-02-05 05:48

from django.db import migrations, models


def migrate_name_to_customer_name(apps, schema_editor):
    """Migrate existing 'name' field data to 'customer_name'."""
    Client = apps.get_model('quotations', 'Client')
    for client in Client.objects.all():
        if client.name and not client.customer_name:
            client.customer_name = client.name
            client.save()


def reverse_migrate(apps, schema_editor):
    """Reverse migration - copy customer_name back to name."""
    Client = apps.get_model('quotations', 'Client')
    for client in Client.objects.all():
        if client.customer_name and not client.name:
            client.name = client.customer_name
            client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, help_text='Customer Address', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='customer_name',
            field=models.CharField(default='', help_text='Customer Name', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text='Customer Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, help_text='Customer Name (deprecated)', max_length=255, null=True),
        ),
        # Data migration: Copy name to customer_name
        migrations.RunPython(migrate_name_to_customer_name, reverse_migrate),
    ]
