# Generated by Django 4.2.7 on 2026-02-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_update_client_to_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='customer_name',
            field=models.CharField(help_text='Customer Name', max_length=255),
        ),
    ]
