# Generated by Django 4.2.7 on 2026-02-05 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_remove_client_name_alter_client_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='User Email', max_length=254, unique=True)),
                ('password', models.CharField(help_text='Hashed Password', max_length=255)),
                ('username', models.CharField(blank=True, help_text='Username', max_length=150, null=True)),
                ('first_name', models.CharField(blank=True, help_text='First Name', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Last Name', max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
