# Generated by Django 4.2.7 on 2026-02-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Admin Access - Full permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(default=list, help_text="List of allowed tab IDs (e.g., ['dashboard', 'quotation'])"),
        ),
    ]
