# Generated by Django 4.2.7 on 2026-02-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_remove_user_username_user_is_admin_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sendemail',
            field=models.EmailField(blank=True, help_text='Send Email Address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sendpassword',
            field=models.CharField(blank=True, help_text='Send Email Password', max_length=255, null=True),
        ),
    ]
