# Generated by Django 4.2.7 on 2026-02-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_add_sendemail_sendpassword_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sendnumber',
            field=models.CharField(blank=True, help_text='Send WhatsApp Number', max_length=20, null=True),
        ),
    ]
