# Generated by Django 4.2.7 on 2026-02-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0015_add_sendnumber_to_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='quotation_logo',
            field=models.ImageField(blank=True, help_text='Quotation Logo', null=True, upload_to='company_quotation/'),
        ),
    ]
