# Generated by Django 4.2.7 on 2026-02-06 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0016_add_quotation_logo_to_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Refresh Token', max_length=500, unique=True)),
                ('user_email', models.EmailField(db_index=True, help_text='User Email', max_length=254)),
                ('user_type', models.CharField(help_text="User type: 'user' or 'company'", max_length=20)),
                ('user_id', models.IntegerField(blank=True, help_text="User ID if user_type is 'user'", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Token active status')),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time token was used', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of token creation', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User agent of token creation', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='quotations__token_0b4434_idx'), models.Index(fields=['user_email', 'is_active'], name='quotations__user_em_3433c9_idx'), models.Index(fields=['expires_at'], name='quotations__expires_8dc19d_idx')],
            },
        ),
    ]
