# Generated by Django 5.2.11 on 2026-02-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0019_quotationsend'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quotationsend',
            index=models.Index(fields=['quotation', 'send_type'], name='qsend_quotation_type_idx'),
        ),
        migrations.AddIndex(
            model_name='quotationsend',
            index=models.Index(fields=['sent_at'], name='qsend_sent_at_idx'),
        ),
    ]
