# Generated by Django 5.2.11 on 2026-02-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0020_quotationsend_qsend_quotation_type_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationsend',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='User ID who sent this quotation (null for admin/company sends)', null=True),
        ),
    ]
