# Generated by Django 5.2.11 on 2026-02-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0021_quotationsend_user_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quotationsend',
            index=models.Index(fields=['user_id'], name='qsend_user_id_idx'),
        ),
    ]
