# Generated by Django 5.2.11 on 2026-02-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0022_quotationsend_qsend_user_id_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tagline',
            field=models.CharField(blank=True, help_text='Company Tagline', max_length=255, null=True),
        ),
    ]
