# Generated by Django 5.2.11 on 2026-02-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0023_company_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, help_text='Company Address', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company Name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Company Phone Number', max_length=20, null=True),
        ),
    ]
