# Generated by Django 5.2.11 on 2026-02-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0024_company_address_company_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='openrouter_api_key',
            field=models.CharField(blank=True, help_text='OpenRouter API Key', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='openrouter_model',
            field=models.CharField(blank=True, default='google/gemini-flash-1.5:free', help_text='OpenRouter Model Name', max_length=255, null=True),
        ),
    ]
