# Generated by Django 5.2.11 on 2026-02-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0025_add_openrouter_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency_symbol',
            field=models.CharField(blank=True, default='₹', help_text='Currency Symbol (e.g., $, ₹, €)', max_length=10, null=True),
        ),
    ]
