// src/constants/permissions.js

export const PERMISSIONS = {
  // Dashboard
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  // User Management
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_EDIT: "USER_EDIT",

  // Role Management
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_EDIT: "ROLE_EDIT",

  ROLE_PERMISSION_MANAGE_VIEW: "ROLE_PERMISSION_MANAGE_VIEW",
  ROLE_PERMISSION_MANAGE_CREATE: "ROLE_PERMISSION_MANAGE_CREATE",
  ROLE_PERMISSION_MANAGE_EDIT: "ROLE_PERMISSION_MANAGE_EDIT",

  // Academic / School
  ACADEMIC_VIEW: "ACADEMIC_VIEW",
  YEAR_SETUP_VIEW: "YEAR_SETUP_VIEW",
  YEAR_SETUP_CREATE: "YEAR_SETUP_CREATE",
  YEAR_SETUP_EDIT: "YEAR_SETUP_EDIT",

  CLASS_MANAGEMENT_VIEW: "CLASS_MANAGEMENT_VIEW",
  CLASS_MANAGEMENT_CREATE: "CLASS_MANAGEMENT_CREATE",
  CLASS_MANAGEMENT_EDIT: "CLASS_MANAGEMENT_EDIT",
  SECTION_MANAGEMENT_VIEW: "SECTION_MANAGEMENT_VIEW",
  SECTION_MANAGEMENT_CREATE: "SECTION_MANAGEMENT_CREATE",
  SECTION_MANAGEMENT_EDIT: "SECTION_MANAGEMENT_EDIT",
  SUBJECT_MANAGEMENT_VIEW: "SUBJECT_MANAGEMENT_VIEW",
  SUBJECT_MANAGEMENT_CREATE: "SUBJECT_MANAGEMENT_CREATE",
  SUBJECT_MANAGEMENT_EDIT: "SUBJECT_MANAGEMENT_EDIT",
  CLASS_SUBJECT_MANAGEMENT_VIEW: "CLASS_SUBJECT_MANAGEMENT_VIEW",
  CLASS_SUBJECT_MANAGEMENT_CREATE: "CLASS_SUBJECT_MANAGEMENT_CREATE",
  CLASS_SUBJECT_MANAGEMENT_EDIT: "CLASS_SUBJECT_MANAGEMENT_EDIT",

  CLASS_TEACHER_MAPPING_VIEW: "CLASS_TEACHER_MAPPING_VIEW",
  CLASS_TEACHER_MAPPING_CREATE: "CLASS_TEACHER_MAPPING_CREATE",
  CLASS_TEACHER_MAPPING_EDIT: "CLASS_TEACHER_MAPPING_EDIT",
  TIME_TABLE_VIEW: "TIME_TABLE_VIEW",
  TIME_TABLE_CREATE: "TIME_TABLE_CREATE",
  TIME_TABLE_EDIT: "TIME_TABLE_EDIT",
  ADD_TEACHER_VIEW: "ADD_TEACHER_VIEW",
  ADD_TEACHER_CREATE: "ADD_TEACHER_CREATE",
  ADD_TEACHER_EDIT: "ADD_TEACHER_EDIT",
  TEACHERS_LIST_VIEW: "TEACHERS_LIST_VIEW",
  TEACHERS_LIST_CREATE: "TEACHERS_LIST_CREATE",
  TEACHERS_LIST_EDIT: "TEACHERS_LIST_EDIT",

  // Students
  ADD_STUDENT_CREATE: "ADD_STUDENT_CREATE",
  ADD_STUDENT_VIEW: "ADD_STUDENT_VIEW",
  ADD_STUDENT_EDIT: "ADD_STUDENT_EDIT",
  STUDENT_LIST_VIEW: "STUDENT_LIST_VIEW",
  STUDENT_LIST_CREATE: "STUDENT_LIST_CREATE",
  STUDENT_LIST_EDIT: "STUDENT_LIST_EDIT",
  
  ATTENDANCE_VIEW: "ATTENDANCE_VIEW",
  ATTENDANCE_CREATE: "ATTENDANCE_CREATE",
  ATTENDANCE_EDIT: "ATTENDANCE_EDIT",
  // Fees & Finance
  FEES_VIEW: "FEES_VIEW",

  // Examination
  EXAMINATION_VIEW: "EXAMINATION_VIEW",

  // Homework & Assignment
  HOMEWORK_VIEW: "HOMEWORK_VIEW",

  // Notification
  NOTIFICATION_VIEW: "NOTIFICATION_VIEW",

  // Transport
  TRANSPORT_VIEW: "TRANSPORT_VIEW",
};
